AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  WyzeSecure Shared API Gateway - Foundation infrastructure only

Parameters:
  StackPrefix:
    Type: String
    Default: wyzesecure
    Description: Prefix for resource names to avoid conflicts
  CorsOrigin:
    Type: String
    Default: "*"
    Description: CORS origin for API responses (set to specific domain in production)

Resources:
  # Single API Gateway for all environments
  ApiGateway:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "${StackPrefix}-api"
      Description: "WyzeSecure API - Multi-stage Gateway"
      EndpointConfiguration:
        Types:
          - REGIONAL
      Policy:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 'execute-api:Invoke'
            Resource: '*'

  # Proxy resource for /proxy path
  ProxyResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: 'proxy'

  # OPTIONS method for CORS preflight on /proxy
  ProxyOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ProxyResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        PassthroughBehavior: WHEN_NO_MATCH
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: !Sub "'${CorsOrigin}'"
              method.response.header.Access-Control-Allow-Credentials: "'true'"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Credentials: true

  # Root OPTIONS method for CORS preflight
  RootOptionsMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !GetAtt ApiGateway.RootResourceId
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        PassthroughBehavior: WHEN_NO_MATCH
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              method.response.header.Access-Control-Allow-Headers: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              method.response.header.Access-Control-Allow-Methods: "'GET,POST,PUT,DELETE,OPTIONS'"
              method.response.header.Access-Control-Allow-Origin: !Sub "'${CorsOrigin}'"
              method.response.header.Access-Control-Allow-Credentials: "'true'"
        RequestTemplates:
          application/json: '{"statusCode": 200}'
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            method.response.header.Access-Control-Allow-Headers: true
            method.response.header.Access-Control-Allow-Methods: true
            method.response.header.Access-Control-Allow-Origin: true
            method.response.header.Access-Control-Allow-Credentials: true

  # Base deployment - includes only foundation methods
  ApiGatewayBaseDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ProxyOptionsMethod
      - RootOptionsMethod
    Properties:
      RestApiId: !Ref ApiGateway
      Description: "Base deployment for shared API Gateway"

Outputs:
  ApiGatewayId:
    Description: ID of the shared API Gateway
    Value: !Ref ApiGateway
    Export:
      Name: !Sub "${AWS::StackName}-ApiGatewayId"

  ApiGatewayRootResourceId:
    Description: Root resource ID of the API Gateway
    Value: !GetAtt ApiGateway.RootResourceId
    Export:
      Name: !Sub "${AWS::StackName}-ApiGatewayRootResourceId"

  ApiGatewayBaseDeploymentId:
    Description: Base deployment ID for the shared API Gateway
    Value: !Ref ApiGatewayBaseDeployment
    Export:
      Name: !Sub "${AWS::StackName}-ApiGatewayDeploymentId"

  ProxyResourceId:
    Description: Proxy resource ID (/proxy)
    Value: !Ref ProxyResource
    Export:
      Name: !Sub "${AWS::StackName}-ProxyResourceId"

  ApiGatewayRestApiUrl:
    Description: Base URL of the API Gateway (without stage)
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com"
    Export:
      Name: !Sub "${AWS::StackName}-ApiGatewayRestApiUrl"
